CREATE TABLE tb_theatre (id_theatre INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nm_theatre VARCHAR(100) NOT NULL,
	ds_address VARCHAR(255) NOT NULL);

CREATE TABLE tb_event (id_event INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tp_rating VARCHAR(3) NOT NULL,
	nm_event VARCHAR(100) NOT NULL, ds_event VARCHAR(255) NOT NULL, qt_duration INTEGER NOT NULL,
	id_theatre INTEGER NOT NULL REFERENCES tb_theatre(id_theatre));

CREATE TABLE tb_session (id_session INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, dt_session DATE NOT NULL,
	id_event INTEGER NOT NULL REFERENCES tb_event(id_event), hr_start TIME NOT NULL, hr_end TIME NOT NULL);

CREATE TABLE tb_chair (id_chair INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nm_row CHAR(1) NOT NULL,
	nr_chair INTEGER NOT NULL, id_theatre INTEGER NOT NULL REFERENCES tb_theatre(id_theatre),
	tp_chair_condition VARCHAR(10) NOT NULL);
	
CREATE TABLE tb_chair_session (id_chair_session INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_chair INTEGER NOT NULL REFERENCES tb_chair(id_chair), id_session INTEGER NOT NULL REFERENCES tb_session(id_session),
	tp_chair_status VARCHAR(20) NOT NULL);

CREATE TABLE tb_price (id_price INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nm_weekday CHAR(3) NOT NULL,
	hr_start TIME NOT NULL, vl_price NUMERIC(10,2) NOT NULL, id_event INTEGER NOT NULL REFERENCES tb_event(id_event));

CREATE TABLE tb_ticket (id_ticket INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_session INTEGER NOT NULL REFERENCES tb_session(id_session), id_chair_session INTEGER NOT NULL REFERENCES tb_chair_session(id_chair_session),
	nr_ticket INTEGER NOT NULL, vl_price NUMERIC(10,2) NOT NULL);
